# Generated by Django 2.1.5 on 2019-03-13 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0004_remove_operator_onduty'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='title',
            field=models.CharField(default='默认标题', max_length=32, unique=True, verbose_name='标题'),
        ),
    ]
