# Generated by Django 2.1.5 on 2019-03-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0005_workorder_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='end_time',
            field=models.DateTimeField(default=None, verbose_name='结束时间'),
        ),
    ]
