# Generated by Django 2.1.5 on 2019-03-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0007_auto_20190314_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='release_addr',
            field=models.CharField(max_length=128, verbose_name='发版地址(SVN/GIT)'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='release_attention',
            field=models.CharField(max_length=128, verbose_name='发版注意事项'),
        ),
    ]
