# Generated by Django 2.1.5 on 2019-03-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0008_auto_20190315_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='passwd',
            field=models.CharField(max_length=20, null=True, verbose_name='运维密码'),
        ),
    ]
