# Generated by Django 2.1.5 on 2019-03-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0009_operator_passwd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='passwd',
            field=models.CharField(default=models.CharField(max_length=20, unique=True, verbose_name='运维名'), max_length=20, verbose_name='运维密码'),
        ),
    ]
