# Generated by Django 2.1.5 on 2019-03-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_order', '0011_auto_20190315_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='passwd',
            field=models.CharField(max_length=20, verbose_name='运维密码'),
        ),
    ]
